# Generated by Django 4.0.5 on 2022-08-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_productos_created_productos_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
