# Generated by Django 4.0.5 on 2022-08-10 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0004_alter_producto_disponibilidad_alter_producto_precio'),
        ('pedidos', '0002_rename_pedido_id_linepedido_pedido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinePedido',
            new_name='LineaPedido',
        ),
    ]
