# Generated by Django 4.0.5 on 2022-08-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='post',
            name='contentenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
