# Generated by Django 4.0.5 on 2022-08-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
